### ISSUE TITLE
some issues when using in RTL screen

### ISSUE THREAD

**Issue by aria125** [dokufreaks/plugin-discussion#127]
There are some issues when I am trying to use the plugin in rtl screen:
1- the threats are located in the right but the buttons dont move to the left, so the last line of comments is over the buttons.
2- There are no Indent for replying comments. The Indent should be considerd in right for rtl screen.

**Comment by Klap-in** [comment]
Improved rtl in #333

In admin is inline order of items not yet correct rtl , no idea how to solve that.
