### ISSUE TITLE
page automatically submit when clicking on a toolbutton with submenus in the editor 

### ISSUE THREAD

**Issue by siggi11** [dokufreaks/plugin-discussion#129]
Same as: arnobaze commented on Dec 12, 2013
the page automatically submit when clicking on a toolbutton with submenus in the editor toolbar.... (other pages o.k)
context: Release rc2013-10-28 "Binky" of dokuwiki and the version 2013-02-15 of the discussion module

**Comment by Klap-in** [comment]
Probably solved.
