### ISSUE TITLE
Changing the title in the configuration

### ISSUE THREAD

**Issue by InfoLibre** [dokufreaks/plugin-discussion#150]
I would like to change the title "discussion" into "Commentary" in all Wiki page.

Instead of adding ''DISCUSSION|Custom Title String'' in each Wiki page, would it be possible to change the title in the configuration of plugin-discussion ?

**Comment by Klap-in** [comment]
Can already be changed by overriding the language string in a `/conf/plugin_lang/discussion/en/lang.php`.
