### ISSUE TITLE
Adding style to comments to be answered

### ISSUE THREAD

**Issue by Braintelligence** [dokufreaks/plugin-discussion#166]
When answering a comment you don't see any indication to what comment you will be answering (except the positioning of the comment editor, which doesn't have any effect if the comment to be answered is the one at the bottom).

There are three ways to change this from what I gather:
1. Add a class to the comment to be answered so you can style it in CSS.
2. Do not remove all the answer buttons. Instead remove only the answer button of the one comment that is to be answered. (And exchange the removed button with a button to return back to comment mode.)
3. Show the comment to be answered next to the comment editor.
All three changes can be used simultaneously.

As it stands now there is only one indication to what comment you're answering to: the comment editor's position. This is not enough.

Also there is no button to return back from the answering mode to normal comment mode, which is not user friendly.

**Comment by Klap-in** [comment]
- Added a class to comment to be answered and the comment form, to give them a darker color
- Added a Cancel button to the reply/edit form
See #333
