### ISSUE TITLE
threads doesn't work

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [dokufreaks/plugin-discussion#167]
Hi,

in my wiki the command {{threads>*}} doesn't work. I cleared the cache, disabled all other plugins, tried different syntax options. But there are no discussions in the output, only the option to create a new page. 
So what can I do?

Regards
Juergen

**Comment by Jona723** [comment]
Hi,

Same problem here. Syntax is not working. Only thing it gives is the 'create new discussion form' (even when it's turned off in settings).
Any help on how to fix this?

Jonathan

**Comment by Fiveflower** [comment]
....same here. In an old test backup copy it work, but in the current working Environment no threads are shown. I cleared data/Cache and even tried to trigger a page by just changeing it. --> Nothing worked

Steven

**Comment by senorandy** [comment]
Remove
utf8_encodeFN()
from line 105 in helper.php then it should work again.

**Comment by Fiveflower** [comment]
Great! It workes well for me!

**Comment by michitux** [comment]
Could you please check if changing the line to
```php
$dir = $conf['datadir'].utf8_encodeFN(($ns ? '/'.str_replace(':', '/', $ns): ''));
```
also works? As far as I can see `utf8_encodeFN()` is there for a reason (but only relevant if the [deaccent option](https://www.dokuwiki.org/config:deaccent) is set to 0, but don't try this out if you don't know what you are doing), however applying it to the whole path is wrong.

**Comment by senorandy** [comment]
yep, works too. My deaccent is set to default (1).
