### ISSUE TITLE
Guest user name showing as "test::"

### ISSUE THREAD

**Issue by zjays** [dokufreaks/plugin-discussion#182]
Guest user name is showing as "test::" if I unselect the configuration option "display real name instead of user name of registered wiki users". 

I'm not sure what exactly the expected behavior should be for this, but I'm assuming the above is not it?

**Comment by PhilipMay** [comment]
The bug is in file "action.php" line 288. There you have to remove the "test" string.

**Comment by Klap-in** [comment]
https://github.com/dokufreaks/plugin-discussion/blob/d8643ff8a53f57f502ed6b5756ec0bb02c749ed6/action.php#L288

**Comment by Klap-in** [comment]
See also #296, #279 and #254. In coming update PR #333 this part is rewritten.
