### ISSUE TITLE
Call discussions by php

### ISSUE THREAD

**Issue by jlAlice** [dokufreaks/plugin-discussion#185]
I need to part discussions from the content block.
What is the php code to show discussions by editing main.php file?

**Comment by Klap-in** [comment]
Currently it is a hook in event system that add after rendering of the page additional piece of html for the comments.

See https://github.com/dokufreaks/plugin-discussion/blob/master/action.php
So it is not just a simple call, but maybe you can reach something with a bit of experimenting?

**Comment by jlAlice** [comment]
Thanx, i'm not familiat with php or other coding so it's hopeless.

**Comment by Klap-in** [comment]
If #333 is merged, you can use action_plugin_discussion::renderCommentsSection()` for this purpose. Not tested, no guarantees.

**Comment by jlAlice** [comment]
Thank you!
