### ISSUE TITLE
"Discussion"/"Back to Article" button

### ISSUE THREAD

**Issue by MrDGray** [dokufreaks/plugin-discussion#188]
It appears that there is an issue where a page (for example "home") is not within a namespace - The "discussion" button will go to the Discussion thread for the page (Discussion:home) which contains the discussion syntax. On pressing "return to article" nothing happens - I've built a test environment and this issue does not arise if the page is in it's own namespace (i.e wiki:home).

**Comment by Klap-in** [comment]
Which template are you using?

**Comment by MrDGray** [comment]
It appears that the template being used is taratasy - I had assumed that
the button was from the settings of the plugin, but it makes more sense if
it is part of the template.

After considering it over night, I suspect that I may be better off just
moving the existing pages into a new namespace and fixing the links as
required.
