### ISSUE TITLE
Ignoring "automatic" and DISCUSSION:off

### ISSUE THREAD

**Issue by Arano-kai** [dokufreaks/plugin-discussion#203]
Plugin ver: 2015-05-17
Wiki ver: Release 2015-08-10a "Detritus"
OS: Ubuntu 14.04.3 LTS (docker container mprasil/dokuwiki)

Simply ignores `automatic` in config and `~~DISCUSSION:off~~` on pages.
There is no *.comments in /data/meta (since there is no comments yet)
What tried: `~~NOCACHE~~`, reinstall, wipe-install.
Temporary solution: `~~DISCUSSION:closed~~`

**Comment by mihula** [comment]
Seems to me, it needs some comment to be able to switch discussion off.
Instead of CLOSED switch you can also add comment first and after that OFF start "working".

**Comment by Arano-kai** [comment]
I'm suppose to enable disscuss by default and disable on some specific pages (like main, etc.). So no comment supposed to be there and disscuss frame need not showing up if `~~DISCUSSION:off~~` provided.
It's a ~~trap~~bug©

**Comment by Klap-in** [comment]
Fixed in #333
