### ISSUE TITLE
"excluded_ns" Setting Causing Comment Status to be Set Incorrectly

### ISSUE THREAD

**Issue by srice01** [dokufreaks/plugin-discussion#204]
When I am using "excluded_ns" it is causing unexpected behaviour in that, when saving this setting into the global "local.php" DokuWiki configuration file, it updates the status of existing comments to "0" (thereby preventing their display) even if the file is not in one of the namespaces specified in the "excluded_ns" pattern.

The problem appears to be with this line in isDiscussionEnabled():

`$isNamespaceExcluded = preg_match($this->getConf('excluded_ns'), $INFO['namespace']);`

In this case "$INFO['namespace']" appears to be set to the page we are currently displaying when changing the configuration but the isDiscussionEnabled() function is being called by the DOKUWIKI "PARSER_METADATA_RENDER" event via function "update_comment_status" to see if other pages (not currently displayed) are to have their status changed as a result of this configuration change.

I got this to work by adding a "global $ID" to the isDiscussionEnabled() function then changing the above line to:

`$isNamespaceExcluded` = preg_match($this->getConf('excluded_ns'), getNS($ID));

**Comment by Klap-in** [comment]
Thanks, I fixed an undefined notice in f8c74f2e3422ec044a28e4476a54ab3fd167c333, part of #333, but see now it creates real issues too, and good confirmation to see the same solution.
