### ISSUE TITLE
'HTTP ERROR 500' in latest version dokuwiki.

### ISSUE THREAD

**Issue by lattekun** [dokufreaks/plugin-discussion#209]
Hello.
First of all, my English is very bad.
But thank you for your reading.

I updated yesterday to latest version dokuwiki(2016-06-26).
I made user guestbook page using 'discussion' plugin since before version.

But this version wiki can`t write 'discussion'.
Test page : http://www.animint.net/test/

If you write 'discussion' and save,
You can see 'HTTP ERROR 500' page.
(I had tested in Chrome.)

I think, it is not a problem with other plugin or cache.
What should I do?

**Comment by jeffreybergamini** [comment]
Can confirm. Issue is at `action.php:1403`:

Code is currently:
`$xhtml = $this->render_text($raw);`

Works when changing the call to `render_text` instead:
`$xhtml = $this->render_text($raw);`

The latter function has warning "very ineffecient for small pieces of data - try not to use" in dokuwiki/inc/plugin.php, FYI.

**Comment by delaffe** [comment]
Thank you, @jeffreybergamini! It works.

**Comment by splitbrain** [comment]
can you send a pull request please?

**Comment by jeffreybergamini** [comment]
Indeed! Just sent one.

**Comment by albig** [comment]
@jeffreybergamini Where is you pull request gone? Can't find it here :-(

**Comment by michitux** [comment]
It has been merged, and therefore closed. So this issue should also be fixed, but we still need to release a new version (though you will already get the new code when you upgrade or install the plugin).

**Comment by albig** [comment]
You're right. I didn't see it, as the pull request #210 has no relation to this issue.
For me this commit resolves this issue.

**Comment by michitux** [comment]
Thanks for the reminder, I've just released a new version (here + on dokuwiki.org).
