### ISSUE TITLE
{{threads>*}} show deleted discussions

### ISSUE THREAD

**Issue by sa7lej** [dokufreaks/plugin-discussion#226]
We use this plugin and like it a lot - we use it (among other things) for suggesting changes on pages. 

We have a page that lists all discussions using {{threads>*}} and that page also shows discussions that have been deleted. Is there a way not to show deleted discussions?

**Comment by Chris75forumname** [comment]
Hi,

 **I have the same problem. Why is this issue open since April 2017???**

I use {{threads>*&table}} on my Start page. Apparently, if comments are deleted on the page of origin, they are not removed from this list on the Start page. Is this a bug or did I just mess too much with the code and screwed it up myself??
Yours, Chris

**Comment by Chris75forumname** [comment]
This is  a serious bug: the plugin uses filemtime() to get the date of last comment.
`$date = filemtime($file);`
This date is used for sorting the comments for the list of comments. However, when a comment was deleted, the page is still listed by the date of the deleted comment.
I programmed a workaround, which looks up the name and date of last comment in the .comments file
`data/meta/*/*.comments`
It relies heavy on string commands. It is not pretty, but it does the job:
`
        $d_file = metaFN($id, '.comments');
        $d_string = io_readFile($d_file, false);       
        $search_string_date = '"date"';
        $delimiter_date = '}';
        $pos_last_date = strrpos($d_string, $search_string_date);            
// Finds position of last occurence of a search word inside of string, die Position ist eine Zahl
        $length_d_string = strlen($d_string);
        $date_string = substr($d_string, $pos_last_date, $length_d_string);  
// trims the front end of the string
//      var_dump($date_string);
        $end_position_of_date = strcspn($date_string, $delimiter_date);      
// Print the number of characters found before the search character
        $start_position_of_date = $end_position_of_date - 11;
        $last_comment_date = substr($date_string, $start_position_of_date, 10);  
// substr(string,start,length) trims the front end and the back end of the string
        $date = $last_comment_date;
`

**Comment by Klap-in** [comment]
In the getThreads() function you have already the unserialized data.
So you could use:
```php
  //new comments are added to the end of array
            $date = false;
            if(isset($data['comments'])) {
                $latestcomment = end($data['comments']);
                $date = $latestcomment['date']['created'] ?? false;
            }
            if(!$date) {
                $date = filemtime($file);
            }
```
Will be added to #333
