### ISSUE TITLE
3 PRs awaiting merging

### ISSUE THREAD

**Issue by moisesbr-dw** [dokufreaks/plugin-discussion#232]
Please merge my PRs #229, #230 and #231.
All three are minimal and fix bugs found during testing.

I will also review the translations for Esperanto and brazilian portuguese someday.

Thanks!

**Comment by Klap-in** [comment]
Translations can been added or modified via the translation tool of DokuWiki at https://translate.dokuwiki.org/

Further interesting improvements, thanks!

**Comment by moisesbr-dw** [comment]
Thanks for the merging of #229 and #231.

#230 still awaits...
I have added screenshots to better show the result of that change.

**Comment by Klap-in** [comment]
If input needed for #230, please ask there.
