### ISSUE TITLE
Adding a discussion to a specif page

### ISSUE THREAD

**Issue by FrankGaul** [dokufreaks/plugin-discussion#239]
Hello,
I cannot add a discussion to a specific  page using the `~~DISCUSSION~~` instruction.  However, if I enable the "discussion section on every page by default" setting, a discussion appears on every page.

thank you for help
Frank

**Comment by FrankGaul** [comment]
Hello, i insert ~~DISCUSSION~~ in a page but nothing appear!
Thank you very much for your help
![image](https://user-images.githubusercontent.com/32487085/31181671-34ddc58c-a922-11e7-9b4e-27533ecea3de.png)

**Comment by Matze1224** [comment]
Hey,
what an editor do you use? Just to reproduce this in fact the editor doesn't look like my editor.
Is the text `~~DISCUSSION~~` displayed when you preview the page?

**Comment by Klap-in** [comment]
(This is the https://www.dokuwiki.org/plugin:ckgedit)
`~~DISCUSSION~~` should be typed without any markup. So typing it directly works for me. If I layout it with an mono font/code style, it is not recognized.
