### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by dsstw** [dokufreaks/plugin-discussion#243]
Hi,

whenever i try to save a comment i get a HTTP ERROR 500.
Using the Version from 2017-08-24.

In know not much information - but any ideas?

TW

**Comment by LarsGit223** [comment]
Hello,

compared to the previous release there have only been translation updates. Does the release before release 2017-08-24 work?

**Comment by Klap-in** [comment]
Which version of DokuWiki do you use?

**Comment by dsstw** [comment]
The latest version from 02/2017.
I just installed it on the homepage.

**Comment by Klap-in** [comment]
Please reopen if there is info from the server error.log.
