### ISSUE TITLE
Discussion entry may disappear, and the edit box also

### ISSUE THREAD

**Issue by rjmaris** [dokufreaks/plugin-discussion#244]
When a regular expression like this one **/^$/** (block discussion at root level, while discussion enabled on every page) is used, any entry that is entered, or was present already (on any namespace, of course) will disappear as soon as the article has been edited! Since the edit box has gone too, an irreversible latch-up condition is established.

The only route to enable discussion again is deleting the appropriate xxx.comments file.

The behaviour also appears when not the article is edited, but instead an empty regular expression field for "block discussion" will be set to **/^$/**.

Test conditions:
- one comment was present.
- no other regular expression has been tested than **/^$/**.

**Comment by rjmaris** [comment]
Note: Doing the stuff without an entry in the regexp box and putting ~~DISCUSSION:off~~ lines at root pages does not work. This statement generally is ignored when all pages are generically set to allow discussions.

**Comment by Klap-in** [comment]
In #333 I fixed that the namespace was sometimes not set if this regexp is checked. But I guess for most cases that should not have an influence. Maybe it helped exactly here...

I was not able to reproduce this issue in my latest version of Discussion plugin and latest version of Dokuwiki.

**Comment by Klap-in** [comment]
I assume this issue is solved inthe latest version.
