### ISSUE TITLE
Disussion+Blog

### ISSUE THREAD

**Issue by Lazycatsu** [dokufreaks/plugin-discussion#258]
Hi! 
I am using blog plugin and tried to add discussion plugin. When I add new comment in form, I can preview it, but! nothing saves.
May be it depends on template?

**Comment by LarsGit223** [comment]
IMHO it should not depend on the template. Which DokuWiki version are you using? There have been compatibility problems with "Greebo" in both plugins.

**Comment by Klap-in** [comment]
Needs more info, please reopen if available.
