### ISSUE TITLE
Failed to handle action: preview

### ISSUE THREAD

**Issue by finelagusaz** [dokufreaks/plugin-discussion#271]
I get an error when I press the button
 
![image](https://user-images.githubusercontent.com/4328918/44221160-95dc5000-a1bb-11e8-94f2-5f1cd51fbe2d.png)

![image](https://user-images.githubusercontent.com/4328918/44221182-a68cc600-a1bb-11e8-8e4f-979bc369a10e.png)

- DokuWiki version: Release 2018-04-22a "Greebo"
- PHP version 7.1.9

**Comment by LarsGit223** [comment]
This should be fixed. Please re-install current version (even so there is no update message) and re-test.

**Comment by finelagusaz** [comment]
I confirmed that the bug was fixed.
Thank you.

**Comment by tloehr** [comment]
Sorry @LarsGit223, I reinstalled the plugin, but didn't help. I left the plugin active, just in case you wanna try it. Thanks for helping.

www.offene-pflege.de
