### ISSUE TITLE
Some issues with latest plugin version

### ISSUE THREAD

**Issue by TECbill** [dokufreaks/plugin-discussion#286]
I just installed the plugin for the first time and I mentioned the following two issues:

1st issue: When using Firefox 65.0.1 some user entry fields like "Full Name" and "E-Mail" and even "CAPTCHA" plugin are just not shown. On Microsoft Edge all content is being showed without any issues.

2nd issue: On some pages the whole discussion entry is just not being showed. I was not able to find out why this is happening because I cannot see any difference between the pages where it's working without problems and the pages where it don't work. This issue is browser independent, meaning it's happening on both browsers, Firefox and Edge.

**Comment by LarsGit223** [comment]
Please only report one issue per issue tracker issue. Thanks.

**Comment by Klap-in** [comment]
1st: It seems to work fine for me.
2nd: #317 reported that footnotes broke showing the discussion section. Other reasons I have not seen. The footnote case I cannot reproduce. 

Please check all these settings please:
- "automatic" setting: global: on/off 
- "excluded_ns" sets namespaces where the global on/off settings is inverted
- on pages `~~DISCUSSION...~~` syntax can be added to override the on/off, or disable.
- on admin page you can also set on/off/disable quicker for more pages
