### ISSUE TITLE
Redirects to a blank page after posting a comment

### ISSUE THREAD

**Issue by deuts** [dokufreaks/plugin-discussion#288]
I tried this plugin and it seems like every time I post a test comment, it redirects me to the blank page with the address bar pointed at <domain>/doku.php . Hitting the back page once will prompt you to resubmit the form, and hitting it twice instead will get back to the page I'm commenting on with my comment duly posted.

I tried this plugin again in a clean install of Dokuwiki and with only this plugin installed (on top of the bundled plugins) and same thing. Tried it with an _Incognito_ window and same thing.

**Comment by tloehr** [comment]
I have the same problem. The comments are stored, but you end up on a blank page after submitting.

**Comment by LarsGit223** [comment]
This might be related to #271. Please try to re-install the plugin (even though there is no update message) and re-test please.

**Comment by LarsGit223** [comment]
@tloehr: can you check the webserver logs? Do you see any errors?

**Comment by LarsGit223** [comment]
I still cannot re-create the problem.

@tloehr, @deuts: what other plugins do you have installed? What DokuWiki and PHP version do you use? What are the config options set for the discussion plugin?

**Comment by tloehr** [comment]
Hi Lars, thanks for the help. I have 2 dokuwiki sites running on the same webspace. One works fine (flashheart.de) with the plugin , one doesn't.

**Comment by LarsGit223** [comment]
@deuts, @tloehr: this issue should be fixed now. Please re-install current master version.
