### ISSUE TITLE
Guests cannot post comments

### ISSUE THREAD

**Issue by dhow** [dokufreaks/plugin-discussion#290]
Hi guys, 

When logged in I could post comments just fine, but I couldn't when posted as a guest -- using a secret window or from mobile phone. There's response or page transition after pressing the submit button. I disabled as many plugins as possible; cleared cache; hard refresh; reinstalled Discussion plugin, still no joy. 

Not sure if related, I have my `bin` `conf` `data` below web root directory. 

You can test the behavior via this URL: http://sookie.eek.jp/wiki/discussion-comment-test

Dokuwiki: 2018-04-22b "Greebo
Discussion plugin: 2017-08-24
Enabled plugin options: allowguests, showguests, usethreading, userealname -- everything else is disabled
Enabled plugins when tested: ACL Manager, Plain Auth Plugin, Configuration Manager, discussion plugin, Extension Manager, User Manager

Thanks!

**Comment by LarsGit223** [comment]
Hello.

Can you please try to un-install and re-install the discussion plugin? There have been changes in #289 which fixes issue #288. Your issue does not sound exactly the same but I think it's worth trying.

**Comment by dhow** [comment]
Thanks @LarsGit223! I uninstalled and installed the discussion plugin, still can't post comment as a guest.

**Comment by dhow** [comment]
Any other thoughts anyone? 
Thanks in advance.

**Comment by LarsGit223** [comment]
Just re-tested only using your options - still works on my side. One question because I didn't notice it before: in my wiki guests have 3 fields for entering values: _"Real name"_, _"E-Mail"_, _"Enter your comment"_.

I do not see an _"E-Mail"_ field on your test page, how did you disable the field?

**Comment by LarsGit223** [comment]
> I do not see an "E-Mail" field on your test page, how did you disable the field?

@dhow: I am asking this because I cannot place comments as a guest as long as the _"E-Mail"_ field is empty.

**Comment by dhow** [comment]
Nice catch @LarsGit223! After inspecting elements the form being hidden is because I specified it in `conf/userstyle.css`, because I didn't want to force people leave email addresses. Forget things easy when you get old... 

I wonder if there's a way to disable email checking, is this possible out of box?

**Comment by dhow** [comment]
Thanks @LarsGit223 btw for looking into my issue!

**Comment by LarsGit223** [comment]
> I wonder if there's a way to disable email checking, is this possible out of box?

No, I think not. Maybe this link helps you to at least fix it for yourself: https://www.dokuwiki.org/plugin:discussion#is_ist_possible_to_disable_the_email_box_for_guest_comments

**Comment by dhow** [comment]
Thanks @LarsGit223 -- your advice worked! 👍

**Comment by LarsGit223** [comment]
@dhow: how long do you run it with the changes now? Did you encounter any negative side effects?

**Comment by dhow** [comment]
@LarsGit223 -- I have it fixed for a few weeks, it's working like a charm. Captcha is working too. I think it's safe to include it, at least tag it "(experimental)" wouldn't harm. This kind of setting is a must in places like Japan where people don't like to leave their email address no matter what.
