### ISSUE TITLE
Feature Request: Apply formatting to cell

### ISSUE THREAD

**Issue by lizat** [dokufreaks/plugin-discussion#302]
It would be handy if instead of having to double click to enter a cell and then highlight the entire text if clicking the required toolbar format icon would apply to the entire cell contents.

**Comment by LarsGit223** [comment]
I think you might have misunderstood the name of this repository. It is called plugin-discussion because this contains the discussion plugin. This is not the place for general discussion about DokuWiki or all plugins. Please only post issues or problems which relate to the discussion plugin here.

**Comment by lizat** [comment]
I may have misunderstood.... but the request was for a new feature on the discussion plugin. If it is incorrect in some way I apologise

**Comment by splitbrain** [comment]
The discussion plugin has no cells. It adds comments to wiki pages. I don't think you're looking at the right plugin here.
