### ISSUE TITLE
DocuWiki Hogfather Version Compatibility?

### ISSUE THREAD

**Issue by GameDoc-MS** [dokufreaks/plugin-discussion#308]
Has anyone tried to use this plugin with DocuWiki Hogfather Version? I am new to DocuWiki and hesitant to use plugins that are not tested.
THX

**Comment by frank-w** [comment]
i had installed it in hogfather, i can configure it, tried using automatic-setting (show on all pages), but this seems not working

see https://github.com/dokufreaks/plugin-discussion/issues/310

**Comment by Klap-in** [comment]
Seems to work fine, as well on Igor. For php8 improvements are coming.
