### ISSUE TITLE
automatic not working in hogfather

### ISSUE THREAD

**Issue by frank-w** [dokufreaks/plugin-discussion#310]
I have automatic set and no exclude namespace, but discussion is not shown.

For translation plugin i need to add it to template (default dokuwiki). Is this true for discussion too?

**Comment by frank-w** [comment]
Any idea? Actually i delay upgrade to hogfather because of this

**Comment by splitbrain** [comment]
I installed the plugin in a Hogfather wiki just two days ago and automatic mode worked fine!?

**Comment by frank-w** [comment]
It is shown on each page (without adding the special string in page)?

Do i need to enable any special setting?

**Comment by splitbrain** [comment]
> It is shown on each page (without adding the special string in page)?
>
yes

> Do i need to enable any special setting?
>
no, only the checkbox for automatic

**Comment by frank-w** [comment]
mhm, created new dokuwiki dir and installed discussion with latest code...now it works...don't know why it does not before
