### ISSUE TITLE
migrating comments from Disqus/Isso

### ISSUE THREAD

**Issue by gour** [dokufreaks/plugin-discussion#318]
Hello!

Instead of migrating my web sites to Tiki CMS, I've fallen in love with DokuWiki and would like to import my comments used with Hugo (static-site-generator) to DW using blog plugin. Originally, the comments were in Disqus, but I did import them into [Isso](https://posativ.org/isso/) running with Gunicorn, but wonder if I can manually add them and edit fields like name, email and date of comments' submission?

Sincerely,
Gour

**Comment by Klap-in** [comment]
There does not exist such a tool at the moment. If you can program, it might doable. However, the comment format is not documented precisely. You have to test it yourself.

**Comment by gour** [comment]
> There does not exist such a tool at the moment. If you can program, it might doable. 

Well, I have just a few comments to migrate...

> However, the comment format is not documented precisely. You have to test it yourself.

...so was more interested in the correct format to do it manually.

**Comment by michitux** [comment]
When you set the `adminimport` configuration option, you should be able to set all fields manually.

**Comment by gour** [comment]
> When you set the `adminimport` configuration option, you should be able to set all fields manually.

That's it! Thank you.
