### ISSUE TITLE
Discussion is not the last entry in TOC

### ISSUE THREAD

**Issue by drbeco** [dokufreaks/plugin-discussion#324]
Dear devs,

Although the pages in my blog clearly ends with `DISCUSSION`, they insist in staynig in the before-last position of the `TOC`.

![image](https://user-images.githubusercontent.com/5805111/156942833-3ef06326-cf66-4da3-83c2-b99235e84de8.png)

Code at the end of a page, for example:

```
===== Obrigado! =====

Agora é com você! Divirta-se programando!

{{tag>linux git contributing}}

~~DISCUSSION~~
```

If I delete the last header, it doesn't matter, Discussion will move up to be before the the now supposed-new last header.

Thanks for looking into it. If I can help with more information, fell free to ask.

**Comment by drbeco** [comment]
Actually, I would prefer to disable `Discussion` from entering `TOC`  at all.

**Comment by drbeco** [comment]
Update: It seems like the exclamation point inside the header is the cause of the problem.

Using...

```
===== Obrigado =====
```

... fix the problem and `Discussion` becomes the last entry

**Comment by Klap-in** [comment]
In the 'dokuwiki' template I cannot reproduce it. With the bootstrap3 template it happens for me too.

Please report to the bootstrap3 template.
I guess the issue 'TOC Affix' you react on seems different then this issue. So the best is to open a separate issue for this in that tracker.
