### ISSUE TITLE
Configuration setting Automatic wants a Custom Title String option

### ISSUE THREAD

**Issue by tangotribe** [dokufreaks/plugin-discussion#325]
If we want our discussion boxes to have a custom title, and we want boxes included on new pages automatically, then we would like to have an Admin Configuration parameter for the customtitle to use.

**Comment by Klap-in** [comment]
See also in these comments how you can already overwrite existing translated strings with your own text. Does this solve your question?

https://github.com/dokufreaks/plugin-discussion/issues/150#issuecomment-65004763

**Comment by Klap-in** [comment]
Also FAQ are updated: https://www.dokuwiki.org/plugin:discussion#howto_rename_all_discussion_section_titles
