### ISSUE TITLE
discussion list function (threads) not working as expected

### ISSUE THREAD

**Issue by Vincent31Fr** [dokufreaks/plugin-discussion#330]
It doesn't seem possible to list open comments for a given or current namespace other than base dir.

With the syntax {{threads>.&}} or {{threads>wiki&}} the function returns nothing (unless the user is admin)

We should be able to use the function for any NS respecting the ACL applied to the user.

**Comment by Klap-in** [comment]
In #333 work in progress. I included your change manually. Welcome to test. I did implement it a bit different, please confirm it is still as expected.

**Comment by Vincent31Fr** [comment]
Tested. It's ok for me !
