### ISSUE TITLE
Email notification is broken 

### ISSUE THREAD

**Issue by Lolcust** [dokufreaks/plugin-discussion#63]
I'm using the discussion plugin with current stable dokuwiki. Installed via plugin manager by means of https://github.com/dokufreaks/plugin-discussion/tarball/master

I have subscriptions turned on, and use Swiftmailer for sending mails. Swiftmailer is configured okay (tested just now by sending myself an email via password change)

However, when adding a comment I get the following
# 

SwiftMailer log:

++ Log level changed to 4
++ Forcing ESMTP mode. HELO is EHLO.
++ Forcing ESMTP mode. HELO is EHLO.
++ Trying to connect...
++ Trying to connect to SMTP server at 'tls://199.195.157.117:465
<< 220 mail.bla-bla.org ESMTP Postfix (Ubuntu)

> > EHLO [199.195.157.183]
> > << 250-mail.tenebrix.org
> > 250-PIPELINING
> > 250-SIZE 10240000
> > 250-VRFY
> > 250-ETRN
> > 250-AUTH PLAIN
> > 250-AUTH=PLAIN
> > 250-ENHANCEDSTATUSCODES
> > 250-8BITMIME
> > 250 DSN
> > ++ SMTP extension 'PIPELINING' reported with attributes [].
> > ++ SMTP extension 'SIZE' reported with attributes [10240000].
> > ++ SMTP extension 'VRFY' reported with attributes [].
> > ++ SMTP extension 'ETRN' reported with attributes [].
> > ++ SMTP extension 'AUTH' reported with attributes [PLAIN].
> > ++ SMTP extension 'AUTH' reported with attributes [PLAIN].
> > ++ SMTP extension 'ENHANCEDSTATUSCODES' reported with attributes [].
> > ++ SMTP extension '8BITMIME' reported with attributes [].
> > ++ SMTP extension 'DSN' reported with attributes [].
> > ++ Trying to authenticate with username 'tbxwiki-noreply'.
> > ++ No authenticators loaded; looking for defaults.
> > ++ Authentication mechanism 'PLAIN' attached.
> > ++ Authentication mechanism 'LOGIN' attached.
> > ++ Authentication mechanism 'CRAM-MD5' attached.
> > ++ Trying 'PLAIN' authentication...
> > AUTH PLAIN ***
> > << 235 2.7.0 Authentication successful
> > ++ Success! Authentication accepted.
# 

And then... nothing happens. The mail never arrives.

The only other clue seems to be in syslog of mail server, which says"
# 

Aug 11 05:52:21 mail postfix/smtps/smtpd[6437]: lost connection after AUTH from unknown[199.195.157.183] 
# Aug 11 05:52:21 mail postfix/smtps/smtpd[6437]: disconnect from unknown[199.195.157.183]

And that's it. Not a single more clue. 

Would you please kindly advise on how to fix it ?

P.S.: something similar happened here: http://irc.dokuwiki.org/?d=2010-12-09
But it has been very long ago and apparently is fixed.

Warm regards,
Lolcust.

**Comment by Klap-in** [comment]
Not enough information for further investigation.
