### ISSUE TITLE
update HTML_EDITFORM_INJECTION event

### ISSUE THREAD

**Issue by Klap-in** [dokufreaks/plugin-discussion#77]
The old event HTML_EDITFORM_INJECTION is still used,  if I am right... this is changed to HTML_EDITFORM_OUTPUT

https://www.dokuwiki.org/devel:event:html_editform_output

i didn't notice problems by this, but probably this event isn't supported anymore by plugins..

**Comment by michitux** [comment]
The event is no longer used now, we currently do not emit any event. Instead of the event for the edit form we should emit a custom event as not everything that is relevant for the edit form is relevant for discussions.
